### ISSUE TITLE
Unable to Save Case using path with spaces

### ISSUE THREAD

**Issue by NWRichmond** [zlotny/DesignSPHysics#18] opened 2017-12-06 23:32 UTC
On Windows 10, attempting to save a case to a path with a space (in the username, e.g., "C:\Users\Firstname Lastname\DesignSPHysics\PracticeCase01") results in an error:

_The path you selected contains spaces. Due to DualSPHysics restrictions, you'll need to use a folder path without any spaces._

Since DualSPHysics itself is fully functional using directories containing this same path with spaces in the username, it seems like an issue that is unique to DesignSPHysics. I wonder if using [os.path functions](https://docs.python.org/2.7/library/os.path.html) such as os.path.normpath(), os.path.relpath(), or similar could be used to get around this issue?

**Comment by ndrs92** [comment] 2017-12-11 10:01
Hi there Nick!

This was a _shortcut_ decision, kind of. At first, when I started developing the application we wanted to have a running version ASAP, so when some problems arised due to spaces in paths we totally skipped that (that's why it has a custom message to apologize for not working...).

I'll have a quick look and try to fix it. Thanks for the reminder!

**Comment by NWRichmond** [comment] 2017-12-12 15:32
Hi Andrés! That makes good sense. Thanks for the response, and I look forward to the fix. In the meantime, I created a separate user account without spaces, and am running cases created with DesignSPHysics without issue.

**Comment by ndrs92** [comment] 2017-12-18 11:55
Hi again!

I found the problem! It's a few lines in the code of DualSPHysics itself. [You can see it here](https://github.com/DualSPHysics/DualSPHysics/blob/13615bacb6cb278982a87aac48d90266b9db5996/SOURCE/DualSPHysics/Source/JCfgRun.cpp#L235)

The problem is that DualSPHysics (and related tools, it's the same code) separates the arguments based on spaces, independently of what the Operating System / Shell tells the program. So when using a path with spaces (For example `"C:\my case\"`) DualSPHysics and its tools understand that there are 2 parameters: `C:\my` and `case\`, when really is only one `char *` because it is surrounded by double quotes.

Going to the interesting thing... I've talked with Jose about this. Is going to get fixed, eventually.

**Comment by NWRichmond** [comment] 2017-12-18 16:59
That's great news! Also, I did some testing and found that using relative paths works well on all the executables, provided that the relative path doesn't extend to the directory with spaces. For example:
- set dualsphysics="../../../../../../DualSPHysics/EXECS/DualSPHysics_win64.exe") **works**
- set dualsphysics="../../../../../First Last/DualSPHysics/EXECS/DualSPHysics_win64.exe") **doesn't work**

This makes me wonder if using os.path.relpath() in DesignSPHysics could be used to get around the issue in DualSPHysics? This wouldn't truly fix the problem, but it could be a good stop-gap measure.

**Comment by ndrs92** [comment] 2017-12-19 10:45
Yes, setting relative paths works without issue. However it is a odd restriction to have yourself limited to folders without spaces for the cases, or even in the case's name.

If the fix is scheduled for too long on DualSPHysics i'll probably implement that workaround, though is no the optimal solution for a lot of reasons.

**Comment by zlotny** [comment] 2018-05-29 08:28
Hi again @NWRichmond!

It's fixed now. DualSPHysics now supports spaces on paths and so does DesignSPHysics.

**Closed by zlotny** 2018-05-29 08:28 UTC
Labels: bug
